### ISSUE TITLE
Feat: Fetch real data from gitlab api

### ISSUE THREAD

**Issue by niklastreml** [NiklasTreml/gitlab-tui#1]
Currently the app uses hardcoded example data. Instead, it should fetch actual live data from a gitlab instance. This issue will serve as a tracking issue.

# Todo
- [x] Authentication
  - [x] Get Gitlab instance from configured remote
  - [x] Use token in ~/.netrc
- [x] Data fetching
  - [x] Evaluate whether we can listen to events, otherwise routinely fetch data
  - [x] Implement data fetching
